kinopoisk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movies.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("", MoviesView.as_view(), name="main"),
    path("detail/<slug:slug>", MovieDetailView.as_view(), name="detail_view"),
    # path("test_for_forms/", ActorsAdd.as_view(), name="test_forms")
    path("review/<int:pk>", ReviewView.as_view(), name="create_review"),

]

movies/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.db.models import CharField, TextField, \
    SlugField, ImageField, DateField, ManyToManyField, \
    ForeignKey, BooleanField, GenericIPAddressField, EmailField, PositiveSmallIntegerField
from django.urls import reverse


class Category(models.Model):
    Name = CharField(
        "Категория",
        max_length=500,
        unique=True
    )
    Description = TextField(
        "Описание",
        blank=True
    )
    Url = SlugField(
        max_length=160,
        unique=True
    )

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["Name"]


class Genre(models.Model):
    Name = CharField(
        "Имя",
        max_length=100,
        unique=True
    )
    Description = TextField(
        "Описание",
        max_length=160,
        blank=True
    )
    Url = SlugField(
        "Ссылка",
        max_length=25,
        unique=True
    )

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = "Жанры"
        verbose_name_plural = "Жанры"
        ordering = ["Name"]

def user_directory_path(instance, filename):
    return f'posters/%Y/%m/%d/{filename}'


class DirectorsActors(models.Model):
    Name = CharField(
        "Имя",
        max_length=100,
        unique=True
    )
    Age = PositiveSmallIntegerField(
        "Возраст",
        default=0
    )
    Description = TextField(
        "Описание"
    )
    Image = ImageField(
        "Фото",
        upload_to="directors/%Y/%m/%d"
    )

    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = "Режиссеры и актеры"
        verbose_name_plural = "Режиссеры и актеры"
        ordering = ["Name"]



class Movie(models.Model):
    Title = CharField(
        "Название",
        max_length=100,
        unique=True
    )
    Tagline = CharField(
        "Слоган",
        max_length=100
    )
    Description = TextField(
        "Описание",
        default=""
    )
    Poster = ImageField(
        "Постеры",
        upload_to=user_directory_path,
        max_length=100
    )
    Year = DateField(
        "Дата выхода",
        default="2021",
    )
    Country = CharField(
        "Страна",
        max_length=30
    )
    Director = ManyToManyField(
        to=DirectorsActors,
        verbose_name="Режиссер",
        related_name="film_director"
    )
    Actors = ManyToManyField(
        to=DirectorsActors,
        verbose_name="Актеры",
        related_name="film_actors"
    )
    Genre = ManyToManyField(
        to=Genre,
        verbose_name="Жанры"
    )
    World_premier = CharField(
        "Премьера",
        max_length=100,
        default=date.today
    )
    Budjet = PositiveSmallIntegerField(
        "Бюджет",
        default=0,
        help_text="Указывать сумму в долларах"
    )
    Fees_in_Usa = PositiveSmallIntegerField(
        "Сборы в США",
        default=0,
        help_text="Указывать сумму в долларах"
    )
    Fees_in_world = PositiveSmallIntegerField(
        "Сборы в мире",
        default=0,
        help_text="Указывать сумму в долларах"
    )
    Category = ForeignKey(
        Category,
        verbose_name="Категория",
        on_delete=models.SET_NULL,
        db_index=True,
        null=True
    )
    Url = SlugField(
        max_length=160,
        unique=True
    )
    Draft = BooleanField(
        "Черновик",
        default=False
    )

    def get_absolute_url(self):
        return reverse("detail_view", kwargs={"slug":self.Url})

    def __str__(self):
        return self.Title

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"
        ordering = ["Title"]

class RatingStars(models.Model):
    Value = PositiveSmallIntegerField(
        "Значение рейтинга",
        default=5
    )

    def __str__(self):
        return self.Value

    class Meta:
        verbose_name = "Количество звезд в рейтинге"
        verbose_name_plural = "Количество звезд в рейтинге"



class Rating(models.Model):
    Ip = GenericIPAddressField(
        "Ip адрес",
        protocol='IPv4',
        null=True
    )
    Stars = ForeignKey(
        to=RatingStars,
        on_delete=models.CASCADE,
        verbose_name="Рейтинг"
    )
    Movie = ForeignKey(
        to=Movie,
        on_delete=models.CASCADE,
        verbose_name="Фильм",
        null=True
    )

    def __str__(self):
        return f"{self.Stars} - {self.Movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

def get_url_for_frames(instance, filename):
    return f"frames/%Y/%m/%d/{filename}"


class FrameOfMovies(models.Model):
    Title = CharField(
        "Заголовок",
        max_length=100
    )
    Description = TextField(
        "Описание",
    )
    Image = ImageField(
        "Кадры",
        upload_to=get_url_for_frames,
        max_length=50)

    Movie = ForeignKey(
        to=Movie,
        verbose_name="",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.Title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"
        ordering = ["Title"]

class Reviews(models.Model):
    Email = EmailField(
        "Email"
    )
    Name = CharField(
        "Имя пользователя",
        max_length=100,
        unique=True
    )
    Text = TextField(
        "Комментарии",
        max_length=5000
    )
    Parent = ForeignKey(
        to='self',
        to_field="Name",
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        verbose_name="Родитель"
    )
    Movie = ForeignKey(
        verbose_name="Фильм",
        to=Movie,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.Name} - {self.Movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


# class BookMark(models.Model):
#     user = ManyToManyField(
#         to=User,
#         verbose_name="Пользователь"
#     )
#     mark = ForeignKey(
#         to=Movie,
#         verbose_name='Избранное'
#     )
#
#     class Meta:
#         abstract = True

movies/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError

from .models import *


class TextName(forms.Form):
    your_name = forms.CharField(
        label="Твое имя",
        help_text="Attention!",
        initial=datetime.date.today,
        max_length=100,
        widget=forms.Textarea,
        required=False,
        error_messages={"required": "Egghead, what did you do?"}
    )

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ["Text", "Name", "Email"]


# class Comment(forms.ModelForm):
#     # slug = CharField(validators=[validate_Age])
#     class Meta:
#         model = DirectorsActors
#         fields = ["Name", "Age", "Description", "Image"]
        # widgets = {
        #     "Name": forms.Textarea(attrs={"cols": 10, "rows": 10}),
        # }
        # labels = {
        #     "Name":_("Имя быстро"),
        #     "Age":_("Возраст какой а?"),
        # }
        #
        # help_texts={
        #     "Name": _("Имя нужно в латинице")
        # }

    #
    # def clean_name(self):
    #     name = self.cleaned_data["Name"]
    #     if len(name)>6:
    #         raise ValidationError("Ты шо правила не читал?")
    #     return name

movies/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, FormView, CreateView
from django.views.generic.base import View
from django.http import HttpResponseRedirect

from .models import *
from .forms import *

class ReviewView(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.Movie_id = pk
            form.Parent_id=form.Name
            form.save()
        return redirect("/")








# def get_name(request):
#     if request.method == "POST":
#         form = TextName(request.POST)
#         if form.is_valid():
#             return redirect("main")
#     else:
#         form = TextName()
#
#     return render(request, 'movies/test_for_forms.html', {"form":form})
#
#
# class ActorsAdd(CreateView):
#     form_class = Comment
#     template_name = "movies/test_for_forms"
#     success_url = redirect("main")


class MoviesView(ListView):
    model = Movie
    queryset = Movie.objects.filter(Draft=False)
    context_object_name = "movies_list"
    allow_empty = False
    ordering = ["Category"]

    # template_name = "movies/Movie_list.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     return context

    # def get(self, request):
    #     movies = Movie.objects.all()
    #     return render(request, "movies/Movie_list.html", {"movies_list": movies})
    # queryset = Movie.objects.get(Url=slug)


# class ReviewFormView(CreateView):
#     form_class = ReviewForm
#     fields = ["Text", "Name", "Email"]
#     template_name = "movie/Movie_detail"

# def get_context_data(self, **kwargs):
#     context =

class MovieDetailView(DetailView):
    model = Movie
    context_object_name = 'movies_detail'
    slug_field = 'Url'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["frames"] = FrameOfMovies.objects.filter(Movie=movies_detail.Movie)

    # template_name = "movies/Movie_detail.html"
    # queryset = Movie.objects.filter(Url= )
    # def get(self, request, slug):
    #     movies = Movie.objects.get(Url=slug)
    #     return render(request, "movies/Movie_detail.html", {"movies_detail":movies})


# class AddReview(View):
#     def post(self, request, pk):
#         print(request.POST)
#
#         return redirect("/")


# class MoviesView(View):
#     def get(self, request):
#         movies = Movie.objects.all()
#         return render(request, "movies/Movie_list.html", {"movies_list": movies})
#
# class MovieDetailView(View):
#     def get(self, request, slug):
#         movies = Movie.objects.get(Url=slug)
#         return render(request, "movies/Movie_detail.html", {"movies_detail":movies})


#
# def index(request):
#     movies = Movie.objects.all()
#
#     context ={
#         "movies":movies
#     }
#
#     return render(request, "movies/Movie_detail.html", context=context)

movies/templates/movies/Movie_detail.html
{% extends 'movies/base.html' %}
{% block title %} {{movies_detail.Title}} {% endblock %}
{% block content %}
		                        <section id="banner">
									<div class="major">
										<header>
											<h1>{{movies_detail.Title}}</h1>
											<p>{{movies_detail.Tagline}}</p>
										</header>
										<p>{{movies_detail.Description}}</p>

										<ul class="descript">
											<li>Год: {{movies_detail.Year}}</li>
											<li>Страна: {{movies_detail.Country}}</li>
											<li>Режиссер:
												{% for director in movies_detail.Director.all %}
													{{director.Name}}
												{% endfor %}
											</li>
											<li>Актеры:
												{% for actor in movies_detail.Actors.all %}
													{{actor.Name}}
												{% endfor %}
											</li>
											<li>Жанр:
											{% for genre in movies_detail.Genre.all %}
													{{genre.Name}}
												{% endfor %}
											</li>
											<li>Премьера в мире: {{movies_detail.World_premier}}</li>
											<li>Бюджет: ${{movies_detail.Budjet}} долларов сша</li>
											<li>Сборы в США: ${{movies_detail.Fees_in_Usa}}</li>
											<li>Сборы в мире: ${{movies_detail.Fees_in_world}}</li>
											<li>Категория: {{movies_detail.Category}}</li><br>
											<li><div>
										<p>Кадры из фильма: </p>
											{% for image in movies_detail.frameofmovies_set.all %}
											<img style="{border-radius:25px;}" src="{{image.Image.url}}" width="150" height="90">
											{% endfor %}
										</div></li>
										</ul>

										<ul class="actions">
											<li><a href="#" class="button big">Перейти к обсуждению</a></li>
									</span>
										</ul>

										<div>
								<form action="{% url 'create_review' movies_detail.pk %}" method="POST">
                                 {% csrf_token %}
                                 <div class="input-group">
                                    <label class="form-label" for="Name">Имя</label>
                                    <input type="text" class="form-control" id="Name" name="Name" required placeholder = "Your name"></input>
                                 </div>
                                 <div class="input-group">
                                    <label class="form-label"   for="Email">Email</label>
                                    <input type="email" class="form-control" id="Email" name="Email" required placeholder = "Text email"></input>
                                 </div>
                                 <div class="input-group">
                                    <label class="form-label" for="Text" required placeholder = "...">Ваш комментарий</label>
                                    <textarea class="form-control"  name="Text" id="Text" rows="5"></textarea>
                                 </div>
                                    <div>
                                       <button class="btn">Отправить</button>
                                    </div>
                                 </form>
							</div>
                           <div>

									<div>

										<ul>
											<img>
											<li>Имя: </li>
											<li>Отзыв: </li>
										</ul>
									</div>
										</div>


									</div>
									<span class="image object">
										<img src="{{movies_detail.Poster.url}}" alt="" />
									</span>

								</section>
{% endblock %}

movies/templates/movies/Movie_list.html
{% extends 'movies/base.html' %}
{% block title %} Видеотека {%endblock%}
{% block content %}
							<!-- Section -->
								<section>

									<header class="major">
										<h2>Какой нибудь жанр</h2>
									</header>
									<div class="posts">
										{% for m in movies_list %}
										<article>
											<a href="#" class="image"><img src="{{ m.Poster.url }}" alt="" /></a>
											<h3>{{ m.Title }}</h3>
											<p>{{ m.Description }}</p>
											<ul class="actions">
												<li><a href="{{ m.get_absolute_url  }}" class="button">Подробнее</a></li>
											</ul>

										</article>
										{% endfor %}

									</div>
								</section>
					{% endblock %}

movies/templates/movies/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>{% block title %} {%endblock%}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'movies/css/bootstrap.css' %}" />
		<link rel="stylesheet" href="{% static 'movies/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'movies/css/formychanges.css' %}">

	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
							{% include 'include/header.html' %}

							<!-1- Banner -->
							{% block detail %}
							{% endblock %}



							{% block content %}
							{% endblock %}
						</div>
					</div>




				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Search -->
								<section id="search" class="alt">
									<form method="post" action="#">
										<input type="text" name="query" id="query" placeholder="Поиск фильма" />
									</form>
								</section>

							<!-- Menu -->
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="index.html">Homepage</a></li>
										<li><a href="generic.html">Generic</a></li>
										<li><a href="elements.html">Elements</a></li>
										<li>
											<span class="opener">Submenu</span>
											<ul>
												<li><a href="#">Lorem Dolor</a></li>
												<li><a href="#">Ipsum Adipiscing</a></li>
												<li><a href="#">Tempus Magna</a></li>
												<li><a href="#">Feugiat Veroeros</a></li>
											</ul>
										</li>
										<li><a href="#">Etiam Dolore</a></li>
										<li><a href="#">Adipiscing</a></li>
										<li>
											<span class="opener">Another Submenu</span>
											<ul>
												<li><a href="#">Lorem Dolor</a></li>
												<li><a href="#">Ipsum Adipiscing</a></li>
												<li><a href="#">Tempus Magna</a></li>
												<li><a href="#">Feugiat Veroeros</a></li>
											</ul>
										</li>
										<li><a href="#">Maximus Erat</a></li>
										<li><a href="#">Sapien Mauris</a></li>
										<li><a href="#">Amet Lacinia</a></li>
									</ul>
								</nav>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>шо это</h2>
									</header>
									<div class="mini-posts">
										<article>
											<a href="#" class="image"><img src="" alt="" /></a>
											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
										</article>

										<article>
											<a href="#" class="image"><img src="" alt="" /></a>
											<p>Aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore aliquam.</p>
										</article>
									</div>
									<ul class="actions">
										<li><a href="#" class="button">More</a></li>
									</ul>
								</section>

							<!-- Section -->
								<section>
									<header class="major">
										<h2>Get in touch</h2>
									</header>
									<p>Sed varius enim lorem ullamcorper dolore aliquam aenean ornare velit lacus, ac varius enim lorem ullamcorper dolore. Proin sed aliquam facilisis ante interdum. Sed nulla amet lorem feugiat tempus aliquam.</p>
									<ul class="contact">
										<li class="icon solid fa-envelope"><a href="#">information@untitled.tld</a></li>
										<li class="icon solid fa-phone">(000) 000-0000</li>
										<li class="icon solid fa-home">1234 Somewhere Road #8254<br />
										Nashville, TN 00000-0000</li>
									</ul>
								</section>

{% include 'include/footer.html' %}
						</div>
					</div>

			</div>


	</body>
</html>

movies/templates/movies/test_for_forms.html
{% extends 'movies/base.html' %}

{% block content %}
<div>
<form action="#" method="post">
    {% csrf_token %}
{{ form }}
    {{form.your_name.errors}}
    <label for="id_your_name">Text your name </label>
    {{form.your_name}}
    {{form.help_text}}


        <button type="submit">Send</button>
</form>
</div>

{% endblock %}